### PR TITLE
Support-non-module-worker-browsers

### PR DESCRIPTION
**Pull request by okikio**
WIP. FIREFOX

### CODE REVIEW

**Comment by jasikpark** [comment]
It seems like this version of the site is erroring for me in Safari & Chrome on macOS

Chrome: 

Screen Shot 2021-10-29 at 9 04 09 PM

Safari: 

Screen Shot 2021-10-29 at 9 05 13 PM

I wonder if there's a way to config netlify previews to direct to `/play` 🤔

**Comment by okikio** [comment]
@jasikpark I'll try to finishing this pr on Monday, would you like to have another dev session to debug this issue.

**Comment by jasikpark** [comment]
> @jasikpark I'll try to finishing this pr on Monday, would you like to have another dev session to debug this issue? As I don't have a Mac to test on Safari

sure!

**Comment by okikio** [comment]
@jasikpark @natemoo-re I had some time this weekend and was able to get it to work on Firefox and Chrome (I need @jasikpark helps to verify that Safari works as well), however, there are bugs when dealing with external components, and these need to be fixed. 

https://user-images.githubusercontent.com/17222836/139572606-ebad6202-0f4d-47d0-af62-779fb494bc00.mp4

**Comment by okikio** [comment]
🚀 You can check out netlify preview at this url: https://deploy-preview-16--astro-repl.netlify.app/play

**Comment by drwpow** [comment]
Ah sorry—I just noticed this PR! If you update this to latest `main` I’d love to test this out. As a Firefox user myself this would be amazing to land! 🤩

**Comment by okikio** [comment]
@drwpow It should be good to merge, however, as I don't have a Mac I can't test out my changes in Safari, I'm not sure if you can, but if you can please try to test in Safari.

**Review by jonathantneal — APPROVED** [review]
Thank you for the updates. I’m going to merge these.

**Pull request merged**
