### PR TITLE
Compiler V0.9.2 upgrade

### PR DESCRIPTION
**Pull request by okikio**
Upgrade to the latest versions of Astro

### CODE REVIEW

**Comment by jonathantneal** [comment]
@okikio, I’m seeing conflicts. Would you work those out? Then I can review this again.

**Comment by okikio** [comment]
Don't merge thus yet, I need to contact @natemoo-re to fix some small bugs

**Comment by okikio** [comment]
You can view preview https://deploy-preview-21--astro-repl.netlify.app/play/

**Comment by okikio** [comment]
Here is a preview of the bug I faced with the new compiler

> You need to go to the Component tab to notice the bug

 https://deploy-preview-21--astro-repl.netlify.app/play/#EQegDghg5gpgziACtGA6CcAuAnA9sALmABkBFAC1IFE4AxOAQQGMAJOAYSYYFcH2GA7tgDicAEIAmMQBViAaQYAvGABEAWsygMqYgGwATaQA0AZgwDyUKgFkxAOwBKATQAMUAEZQA1gE8A6qTCABzs7ADKAJIupGImalQOcl4MAFIAlimKfH5qYBJhlAA2YXBQKgCO5gwqTmIAVioqALZhKU4+DBFymGkMpHZ+EJhBTBFN1gxgDmX6wgxqRhKIuAoqKcliAKoM0hJQrIpB2wxwTDBiAgzCTQ4CxGLWACwArAwMaaQAjLhBtMJqJlYAE5dLI4KQmogxE0NGIAMxMWiffRqFhaABqimkYBSp0YLAAci5Hpc6ilsNgwGpELpNkYWPpHoViNIqCoIilNgAPDxOXEOXApEy4HxQWjoppOCRNJjEGAORAOFxqGBw9FwlJ2bikbL8ALzKhcgROIzSQpeIzYT5OCDYPwE6y4BhclIAN2wXloz1IrvIcwYiAYYiYagcaTSwj8ihYYmuXjgLBcinYTnRhSgQJYuigLlw5CgYQENj8ifMLCCiiouGINTgKi5whUUH0VFIKWImwA1ASnNgBMJuF5SM8h49zDqxFQjFAxDA1OxHhAwExtXwtIVaP2CtYwj4JNIguR2JqCesWIoxFDyBFyOR9MQ-E5yF5yg5sO7sHByGAqASvHIqEUCBaC8dgxGIbh2RSC4mAETZ0UeOwIAcLkID6WwdQYGAIGEGJsEQYgfkUFJHmkCIA0KBgfFwuEwAEOphC8JwnDqKgmCBLwLjSKh2kTaxNicEIJG4lRdAkdhEAkN4GG9TsWBeAB2KgqFItIWGIcxpGSBhaDUXRyGkbAqFobAwl2TZ2G4LpuEKchzDgTZiH0TtEC5KyuTSNQghYSDcAkdEIHYAk6i8ZTs2wKBpG7RQ7HYKBHhUMIuCFUh0QU5gBB8XQUnKUhiHYYgwBMCIYE8bFmLEcwHGeARMAJZ4YAiOwivMTZhAiJwVDsHwgQU8gAFoBBSIJpFIgRsU2JoGG5J1XljIM-H0Y1Cn60h9DEFgBDEBxhCoKBzDAUgoGeJguRUQoXD8FRPTY0Y4WrMQnGEJgTHIJhEDqEwgQYOQBGut4nDgCI6jQpwBDhQqBAiMIwgYCACXOMQwBYNJakeeouCaOpXVITAnSMKg0giT5dAcchvrhiR3GcOBGP+9qdKoIMnFoCIoHIWH1HtAw6kQwQtOEJw-DEfQWFSTZnnIiJSDgbBOGsBk4E7AQWDCAk5GEFh7TCFwgXcbFaHYcwCQiLlcAgLwgktz4UiaB4FKcawmiCdKgigaw4Qcdg5HKEwdpUR5Hi5R4mgiYhrCMcwVkKH1xp8KgfCYTsUhcbB5DEGzymQsAvBUQw5GsHwNEeKBXWAhgXGIKhyhURAoD9hgJHIPxaEeTZcHqlutC0dgHNIUhsQUNJFDAWoUmsQo1NwNRyDhKhaWwZ5yCxCIIAkCI1DETtMCsOBCgkIFrHYUgBG4RBSAibgwj8dwnrgfQ4CcQo-C8OpED8KACQJOxm1II-zCYCkfWusCRUG4OQFQbxChiE5oUcc3IFLjkfikAQ6I4BWwUpgJOYgNY+AEEndgnw-DomeGTGMYBRBpH0BIPY7g5BAm4A0XmVAghAjgHCCIQQrQsGsKQIw0QOgMGAAAGlAEwXATQwC4DsDAOwmAEDsAkVImRcj0BYDwIQEgFBAgKzrLTJgwZtAuHYMIMQ7hJi4FLmzBwDBrByAFBYawwgXBBBgLgCIAhcBOkDI9dgEwzBiA6o3OEXhejuE+GEJwDBXS4E+OQK2WEQbWDANgP8QigA

**Comment by okikio** [comment]
@natemoo-re It's ready for review

**Review by natemoo-re — APPROVED** [review]
Looks great! Thanks ☺️. Feel free to merge whenever you're ready.

**Comment by okikio** [comment]
@natemoo-re I don't have write access, so, I can't merge

**Pull request merged**
